name: Deploy to Lambda

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Lambda Package"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Download artifact from build
      if: github.event_name == 'workflow_run'
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        name: lambda-package
        path: .
        workflow_conclusion: success
        run_id: ${{ github.event.workflow_run.id }}

    - name: Download local artifact
      if: github.event_name == 'workflow_dispatch'
      uses: actions/download-artifact@v3
      with:
        name: lambda-package

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Lambda
      run: |
        bash scripts/upload.sh 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to Lambda
      run: |
        bash scripts/upload.sh 