name: Deploy to Lambda

on:
  push:
    tags:
      - '*'  # This will match any tag that starts with 'v', like v1.0.0, v2.3.1, etc.
      # You can also use '*' to match all tags, or other patterns as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python for local build
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Install dependencies for local build
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv
        source .venv/bin/activate
        uv pip install -r requirements.txt

    - name: Create Lambda package locally
      run: |
        bash scripts/zip.sh

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to Lambda
      run: |
        bash scripts/upload.sh 